[package]
name = "rustc-backtrace-filter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rbf"
path = "src/main.rs"

[dependencies]
atty = "0.2.14"
clap = { version = "4.3.19", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.9.1"
